da/update nixos generators
divnix/digga pull request #63
Opened 2021-06-21 16:42 UTC by blaggacao

- mv fullFlake -> example
- add groupByConfig example
- ref: auxiliaries (checks, jobs, devshell)
- fix classicalDevos example
- fmt
- evalnix
- ref: ci to new shift-left testing strategy | please do TDD form now on
- update: nixos-generator with nixlib dep

2021-07-03 18:54 UTC, Pacman99 commented
I think this needs a rebase and can we drop all the `follows` for nixos-generators. Using `follows` in a library flake breaks things. Until the nix PR fixing `follows` is merged, we shouldn't use it here.

2021-07-04 05:56 UTC, blaggacao commented
bors try

2021-07-04 05:58 UTC, blaggacao commented
bors try-

2021-07-04 05:58 UTC, blaggacao commented
bors try

2021-07-04 06:07 UTC, Pacman99 requested changes

2021-07-04 06:07 UTC, Pacman99 commented on flake.nix
> +        inputs.nixlib.follows = "nixlib";
We need to remove this line too, otherwise `nixlib` will have to be an input for digga users.

2021-07-04 12:28 UTC, blaggacao commented on flake.nix
> +        inputs.nixlib.follows = "nixlib";
Why do you suggest that? This is an actual and accurate dependency.

2021-07-04 16:46 UTC, Pacman99 commented on flake.nix
> +        inputs.nixlib.follows = "nixlib";
Because of the nix issue... every downstream consumer of digga now has to add nixlib as an input. And of they don't their going to get a confusing error of how digga follows a nonexistent input nixlib.

2021-07-04 16:49 UTC, Pacman99 commented on flake.nix
> +        inputs.nixlib.follows = "nixlib";
We really just cant use follows in digga or any library flake until https://github.com/NixOS/nix/pull/4641 is merged.

2021-07-04 19:23 UTC, blaggacao commented on flake.nix
> +        inputs.nixlib.follows = "nixlib";
So basically you're saing that https://github.com/divnix/digga/pull/71 is not an appropriate solution?

2021-07-04 22:22 UTC, Pacman99 commented on flake.nix
> +        inputs.nixlib.follows = "nixlib";
Yeah essentially. I don't think theres much advantage anyways with using follows here. nixlib is so small that it won't matter. I get that its more "correct", but I think we should just wait for the fix upstream before using it here.

2021-07-04 22:51 UTC, blaggacao commented on flake.nix
> +        inputs.nixlib.follows = "nixlib";
Maybe we should help puh the upstream issue, since it's arguably quite an annoying one. :shrug:

2021-07-04 22:59 UTC, Pacman99 commented on flake.nix
> +        inputs.nixlib.follows = "nixlib";
Well I currently consider the use of `follows` in digga to be a major bug, it prevents people from using digga develop because of the error. So is it ok to just remove it for now?

2021-07-07 20:33 UTC, blaggacao commented
This is superseded by #79

2021-07-07 20:33 UTC, closed without merging